# Generated by Django 3.1.6 on 2021-04-08 13:33

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrainement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrainement', django.contrib.postgres.fields.ArrayField(base_field=models.BooleanField(default=False), size=None)),
            ],
        ),
    ]
