# Generated by Django 3.1.6 on 2021-04-08 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_entrainement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quizz', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='entrainement',
            name='entrainement',
        ),
        migrations.AddField(
            model_name='entrainement',
            name='state',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='entrainement',
            name='note',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='login.note'),
        ),
    ]
