# Generated by Django 3.1.6 on 2021-04-10 10:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('login', '0003_auto_20210408_1350'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnneeClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EntrainementClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PartitionClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='WrapperClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('quiz', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='entrainement',
            name='note',
        ),
        migrations.DeleteModel(
            name='Hero',
        ),
        migrations.DeleteModel(
            name='Entrainement',
        ),
        migrations.DeleteModel(
            name='Note',
        ),
        migrations.AddField(
            model_name='partitionclass',
            name='nuance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nuance', to='login.wrapperclass'),
        ),
        migrations.AddField(
            model_name='partitionclass',
            name='structure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structure', to='login.wrapperclass'),
        ),
        migrations.AddField(
            model_name='entrainementclass',
            name='wrapper',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='login.wrapperclass'),
        ),
        migrations.AddField(
            model_name='anneeclass',
            name='instruments',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instruments', to='login.wrapperclass'),
        ),
        migrations.AddField(
            model_name='anneeclass',
            name='note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note', to='login.wrapperclass'),
        ),
        migrations.AddField(
            model_name='anneeclass',
            name='partition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.partitionclass'),
        ),
        migrations.AddField(
            model_name='anneeclass',
            name='rythme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rythme', to='login.wrapperclass'),
        ),
        migrations.AddField(
            model_name='anneeclass',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
